:stem:

= Training endurance skills

Interval training is superior to continuous training for efficiently building endurance. The same performance improvements are achieved with less time investment (e.g.

include::partial$gen/bibliography.adoc[tag=ESECIT]
).

This applies not only to maximum oxygen uptake (VO₂ max), but also to anaerobic capacity. After

include::partial$gen/bibliography.adoc[tag=EMEHIIT]
Four minutes of high-intensity interval training can improve VO2 max just as effectively as 60 minutes of continuous training.

For physical training, we adopt the definitions from

include::partial$gen/bibliography.adoc[tag=HICCA]
, page 8.

* Sprint Interval Training (*SIT*): <30 sec maximum exertion (RPE 10/10), e.g., 30 sec maximum sprint
* Speed endurance training (*SET*): 30-60 seconds at https://www.crossfitwiesbaden.com/blog/rpe-training-was-bedeutet-das[RPE] 9/10, e.g.: 8x 30 seconds with 3-minute breaks
* Muscle Buffer Training (*BUF*): Load with a result of 8 to 10:[ (mmol) / l], at RPE 8/10, e.g., 6x 2 min with 3 min rest
* High-Intensity Interval Training (*HIIT*): Intervals of 2-20 minutes at RPE 9/10, 90% maximum heart rate, or 90-95% VO₂ max, e.g., 4 x 8 minutes with 2-minute breaks

However, the transitions between the different types of training are fluid.

include::partial$motoriktraining/endurance-training/motor-endurance-hiit.adoc[leveloffset=+1]

include::partial$motoriktraining/endurance-training/motor-endurance-hiit-sit.adoc[leveloffset=+1]

include::partial$motoriktraining/endurance-training/motor-endurance-vo2max.adoc[leveloffset=+1]