= Reaktionstraining

Um eine zielgerichtete Reaktion durchzuführen, sind folgende Schritte erforderlich
include::partial$gen/bibliography.adoc[tag=DKVPS]
:

[cols="3,1"]
|===
|Übertragungsweg |Zeit

|Reizaufnahme im Rezeptor | 1 - 40ms
|Übertragung zum Kortex | 1 - 100ms
|zentrale Vorgänge | 70 - 300ms
|efferente Übertragung | 10 - 20ms
|Latenzzeit des Muskels | 30 - 70ms
|===

Die _zentralen Vorgänge_ sind dem Reaktionstraining zugänglich; die Latenzzeit des Muskels ist durch Schnelligkeitstraining zu verbessern. Alle anderen Faktoren sind dem Training nicht zugänglich.

Reaktionszeiten treten nach
include::partial$gen/bibliography.adoc[tag=TBCRTL]
in zwei Arten auf:

* als *Einfachreaktion* (_Simple Reaction_), bei der nur ein möglicher Reiz auftreten kann, der mit genau einer Reaktion zu beantworten ist.
* als *Auswahlreaktion* (_Choice Reaction_), bei der es mehrere mögliche Reize gibt, die potentiell alle eine unterschiedliche Reaktion erfordern.

Die _Einfachreaktion_ ist durch Genetik, Körperaufbau und Anthropometrie vorgegeben und kann nicht signifikant verbessert werden
include::partial$gen/bibliography.adoc[tag=BAPESRT]
. Hier ist lediglich die Latenzzeit des Muskels über das Training der Schnelligkeit verbesserbar. Training für die Einfachreaktion ist daher nicht sinnvoll.

Die _Auswahlreaktion_ ist im Fechtsport gut trainierbar.

Die Reaktionszeit hängt direkt von der Anzahl der Wahlmöglichkeiten ab. Aus
include::partial$gen/bibliography.adoc[tag=DKVPS]
:

include::diag-auswahlreaktion.adoc[]

Ein Reaktionstraining mit zwei Auswahlmöglichkeiten steht Aufgrund der kleinen erzielbaren Verbesserung in keinem guten Verhältnis zum Trainingsaufwand. Auf der anderen Seite sind Angriffe in der Regel innerhalb von 500-600ms abgeschlossen
include::partial$gen/bibliography.adoc[tag=FLOFT]
, was die Zahl der möglichen Reaktionen auf vier bis fünf begrenzt.

Das Training von Auswahlreaktionen trainiert die _zentralen Vorgänge_ und ist damit nicht nur sportartspezifisch, sondern zielt sogar genau auf die auftretenden Stimuli und die dafür vorgesehenen Reaktionen ab. Es ist nicht transferierbar, weshalb ein allgemeines Reaktionstraining keinen Effekt auf das Fechten hat.

*Reaktionstraining im Fechten zielt immer auf die Auswahl von 3 bis 5 möglichen fechterischen Reaktionen auf zugehörige fechtspezifische Reize.*

== Beispiel: Training 3er-Auswahlreaktion

.Organisationform
Partnerübung; Aufstellung in Gassenform

.Durchführung
* A bewegt sich frei (Schritte, Sprünge) in Sixt, B folgt in mittlerer Mensur
* Nach belieben (etwa 5 bis 15 Sekunden) führt B einen direkten Angriff durch, auf den A reagiert:
** Zur Hand: A zieht sich mit zwei schnellen Schritten zurück
** Zum Fuß oder zum Oberschenkel: A reagiert mit Arrêt/ Stoß zur Brust
** Zum Körper: A reagiert mit Quart-Parade/ Gleitstoß Brust

.Variationen
* A in "Lauerstellung"
* A mit Klinge in Oktav, Septim, Terz
* A bewegt sich mit großen Sprüngen
* B variiert den Abstand zwischen eng und überweit
* mit Mini-Waffen
* auf unterschiedlichen Untergründen (Bank, Weichbodenmatten, ...)

.Hinweis
Die gewählten Reaktionen sollen sehr bald durch die Fechter:in selbst festgelegt werden. Sie sind Bestandteil des gewählten, individuellen Fechtsystems. Bei der Partnerübung sollen die Fechter:in drei bis vier Reaktionen auswählen. Sie können bei jeder Paarung unterschiedlich sein.
