= Degen - Trainingsbuch
:description: Methodik, Hintergründe und Inhalte des Degen-Trainings. Für Trainer:innen und interessierte Athlet:innen. Auch für Florett und Degen-Fechten interessant.
:keywords: Fechten,Degen-Fechten,Training,Strategie,Taktik

Zuletzt Aktualisiert: {localdate}

Das Fechten ist eine Sportart mit langer Tradition. Entsprechend werden auch Lehrbücher seit mehreren hundert Jahren verfasst.

Dabei haben sich alle Aspekte des Fechtens gleich mehrfach fundamental gewandelt: Die Zielsetzung wandelte sich vom Kriegseinsatz über Duellsituationen bis zum modernen Sportfechten. Das Material änderte sich bezüglich Klingenlängen und -Geometrien genauso wie hinsichtlich der eingesetzten Materialien vielfach. Immer effektivere Schutzausrüstung ermöglicht inzwischen das gefahrlose Training nahezu jeder Kampfsituation. Entsprechend können im modernen Fechten Techniken und Taktiken eingesetzt werden, die sich früher verboten. Hinzu kommen durch neue Trainingsverfahren und neue Anthropometrie völlig andere körperliche Voraussetzungen.

Deswegen müssen wir für jeden Aspekt des Degenfechtens hinterfragen, ob wir als Ziel tatsächlich Handlungsfähigkeit und Erfolg als maßgebliche Größen betrachten, oder ob wir nicht gelegentlich mehr einem historisch geprägten ästethischen Empfinden nacheifern.

Ziel dieses Buches soll sein, in möglichst jedem Aspekt die effektivsten Taktiken, Techniken und Methoden zu identifizieren und einzusetzen.

Gerade Jugendliche, die Jahre der Ausbildung auf sich nehmen, haben ein Recht darauf, ihre Zeit effizient einzusetzen. Gleichzeitig wollen wir es jedem Menschen ermöglichen, seine/ihre individuellen Vorteile und Möglichkeiten auszuschöpfen.

In zweiter Linie wollen wir verstehen, warum Techniken oder Trainingsmethoden Erfolg zeigen und wir wollen das wissenschaftlich Begründen. Die Umsetzung neuer Erkenntnisse aus der Forschung erscheint uns ein geeigneter Weg, um unser Training stetig zu verbessern. Es soll immer gelten: Das Bessere ist der Feind des Guten.

== Verwendung

* Das Buch kannst Du unter unserer xref:lizenz.adoc[Lizenz], der Creative Commons Share-Alike License verwenden.
* Wenn Du Inhalte in Deinem Training verwenden möchtest, dann erwarten wir, dass Du auf die Quelle hinweist.
* Über Hilfe, Beiträge und Mitarbeit freuen wir uns. Dafür kannst Du https://github.com/n0y/degen-trainingsbuch/[das Degen-Trainingsbuch auf Github] forken und Pull Requests erstellen. https://github.com/n0y/degen-trainingsbuch/blob/main/AUTOREN.adoc[Die Autoren] behalten sich aber vor, über die Aufnahme und Änderung von Inhalten zu entscheiden. Deswegen kann es sinnvoll sein, https://github.com/n0y/degen-trainingsbuch/discussions[eine Diskussion zu starten], bevor Du Dir die Arbeit machst.
* Gerne kannst Du uns für Deine Anliegen, Vorschläge und Korrektur-Hinweise https://github.com/n0y/degen-trainingsbuch/issues[Issues erstellen].

== Autoren

include::partial$gen/AUTOREN.adoc[tags=autoren]
