= Degen - Trainingsbuch

Ziel der hier veröffentlichten Texte ist es, Grundlagen, Ziele, Inhalte und Trainingsmethoden für das Degenfechten zu sammeln.

Haupt-Augenmerk soll darauf liegen, neue Erkenntnisse zu Lernmethoden einzuarbeiten, um den Lernaufwand zu minimieren, die Motivation hoch zu halten und Spaß am Training zu vermitteln.

Das gesamte Projekt ist unter dieser Lizenz veröffentlicht: xref:LICENSE.adoc[] (Englisch:xref:LICENSE.en.adoc[]).

Ausnahme ist das UI-Bundle (`src/ui-bundle`), das als angepasste Version der https://gitlab.com/antora/antora-ui-default[Antora Default UI] unter der xref:src/ui-bundle/LICENSE[Mozilla Public License Version 2.0] steht.

Alle Autoren sind unter xref:AUTOREN.adoc[] einzusehen.

Der jeweils https://www.fintenfisch.de/[aktuelle Stand ist auf unserer Github Page] veröffentlicht.

== Mitarbeit

Jede Art von Mitarbeit ist willkommen. Es ist gut neue Inhalte unter den Issues anzukündigen, wo bereits vorab eine Diskussion möglich ist.

Jederzeit kannst Du gerne auch einen Pull-Request erstellen. Die Maintainer behalten sich eine Entscheidung über die Aufnahme von Beiträgen vor.

*Wenn Du Änderungen vorschlägst, dann trage Dich bitte als erstes in die Autoren-Liste unter xref:AUTOREN.adoc[] ein. Damit stellst Du die Inhalte, die Du beigetragen hast, unter unsere xref:LICENSE.adoc[Lizenz].*
