= Pushing and hitting movements

The key factors that determine whether desired target regions are successfully reached have largely been unexplored to date. There are only a few findings that have been confirmed by studies.

For example, it is known that the technique used for throws does not correlate with that used for hand movements in fencing strikes.

include::partial$gen/bibliography.adoc[tag=KCLFEF]
. It is also known that even during a miss or fléche, the time until the hit occurs (500-600 ms, from

include::partial$gen/bibliography.adoc[tag=FLOFT]
) is sufficient to successfully change the target (200ms, from

include::partial$gen/bibliography.adoc[tag=ACOAEF]
).

== The "arm before leg" rule

The rule "arm before leg" means that in combined striking movements involving arm extension and body movement, the arm extension must be performed before the leg movement begins.

include::partial$gen/bibliography.adoc[tag=GTHOF]
. In the weakened form, the leg movement is started shortly before the arm movement is completed.

include::partial$gen/bibliography.adoc[tag=AKonDFB]
.

An evaluation of all offensive hits in the final round of the World Cup in Doha in 2024 showed that not a single attack involving arm and leg movements was carried out in this manner. Attacks either required only an arm movement or were initiated with the leg.

No attack that only required an arm extension was followed immediately by another attack; instead, the arm was always withdrawn.

The 500-600 ms required for an attack with a fail or flèche are sufficient for several fencing actions. That is why it is important to protect the weapon arm from counterattacks for as long as possible and to maintain maneuverability for as long as possible. Both require at least a half-bent arm, as in

include::partial$gen/bibliography.adoc[tag=ErlFe]
(on the fencing position) explains.

It is advisable to achieve maximum arm extension only at the moment of impact. Since the simple failure takes about 500 ms, while the explosive arm extension takes less than 100 ms

include::partial$gen/bibliography.adoc[tag=AREKinSP]
, the arm should only be extended during the attacking movement.

== Training the thrust and strike movement

The pure thrust and strike movement can be trained through variable thrust exercises. Variability is one of the most important factors here, as striking movements must be performed safely and quickly from a wide variety of situations and body/hand positions.

For striking exercises, it is advisable to perform the exercises in short blocks: several variations are performed for one size across several exercises (e.g., six different striking areas in succession; four different starting blade positions). To do this, a combination of variations is added (e.g., execution with a step forward, slowing down the striking movement, and closing one eye).

The following can serve as aids, for example:

* Markings on the floor that can be used to determine different foot positions by rolling dice
* Different "weapons," e.g., pipes, wooden sticks, pieces of hose
* moving targets, e.g., swinging balls, hitting table tennis balls that are transported into a goal

A timed competition or a competition for the most hits per attempt in small groups has proven successful.

In order to set changing goals, these can be planned in advance. Alternatively, they are displayed, e.g., using a fencing hit target or laser pointer.

Blade actions can also be practiced by placing opponents next to the target in small groups. On the other hand, impact training with a person as the target has not proven successful, as the aversion to potentially hitting or being hit painfully makes it difficult to concentrate on training.

include::partial$techniktraining/technical-training-meeting-movement-unit.adoc[leveloffset=+1]