= Training session: Push-up exercises
:keywords: exercise
:uebung-group: technical training

ifndef::ownpage[]

xref:page$practices/technical-training/technical-training-meeting-movement-unit.adoc[Only this exercise]

endif::[]

.Material (something similar will also work)
* Soft floor mats (on the wall), or similar.
* Tennis balls, Styrofoam balls, or similar items on a string
* Adhesive tape (masking tape, etc.)
* Box, bench, or similar
* matchboxes
* felt-tip pen
* 6-sided dice
* possibly a laser pointer
* possibly different "weapons"

Encounter different targets that are marked. The starting position and thrust variation are varied. The learners form small groups that set themselves tasks. Two to three people are ideal.

.Notes
* A total of 5 minutes should be spent practicing at each station.
* Various "weapons" can be offered: pipes, wooden sticks, etc.
* Playing music while practicing has proven to be effective.
* Unless otherwise specified, the focus should be on *high execution speed*. This is more important than "clean execution." If the exercises are performed too slowly, proprioceptive perception will not correspond to that in real combat situations, leading to slow execution in combat as well.
* If necessary, the execution time can be measured occasionally.

_Station 1: Soft floor mats_

* Five targets are marked between head and foot height using adhesive tape.
* Six spots for the feet are marked and numbered in front of the mat, at intervals between 1 and 3 meters.

The learners take turns.

. Roll the dice to determine your foot position: 1-6 according to the floor markings. If the same number appears twice, it applies to one of the feet: in the air.
. Roll the dice for an additional task (alternatively: the learners come up with tasks themselves)
[numeric]
.. as soon as possible.
.. Weapon on the ground before each hit
.. close your eyes when thrusting
.. hit the line, very slowly and carefully
.. Do a stretch jump between each hit.
.. The unarmed hand grasps the front ankle.
. Ready, set, go as the starting signal

_Station 2: Moving Targets_

* The balls are attached to a string and hung up (e.g., on a handball goal).

The learners take turns. Keep a safe distance!

. Roll the dice to determine the starting position: 1-6 meters between the tip and the ball
. Roll the dice for footwork (if necessary, first correct the distance by taking steps back).
[numeric]
.. step by step
.. with steps and lunges
.. with jump and lunge
.. with steps, step back, lunge
.. with lunge, follow-through, lunge
.. with Fléche
. Ready, set, go as the starting signal

_Station 3: Box_

* The matchboxes are positioned upright on the edge of the box.
* Six spots for the feet are marked in front of the station.

The learners must knock over the matchboxes with one push.

. Roll the dice to determine your foot position: 1-6 according to the floor markings. If the same number appears twice, it applies to one of the feet: in the air.
. Roll the dice for an additional task (alternatively: the learners come up with tasks themselves)
[numeric]
.. as soon as possible.
.. Weapon on the ground before each hit
.. close your eyes when thrusting
.. hit the line, very slowly and carefully
.. Do a stretch jump between each hit.
.. The unarmed hand grasps the front ankle.
. Ready, set, go as the starting signal

Station 4: Laser pointer

* a person receives the laser pointer
* The other person starts in such a way that they are always two meters away from the target during the footwork.
. Rolling the dice for footwork:
[numeric]
.. One step forward, one step back
.. One step forward, one step back
.. One step forward, two steps back
.. Step forward - failure, step back
.. Trippling on the spot
.. free footwork
. Ready, set, go as the starting signal
. After 1-10 seconds, a target appears on the wall.
. Learners must hit this target as quickly as possible with a backhand and remain in the backhand position.
. Immediately afterwards, another destination is displayed.
. Learner must score with a rebound
. 5 repetitions each