= Beinarbeit

Klassische Beinarbeit „auf Ansage“ und ohne Vorgabe von Varianten, gezielt auf die Einhaltung einer Zieltechnik, erzielt schon nach kürzester Zeit keinen technischen Lerneffekt mehr und sollte höchstens untergeordnet eingesetzt werden
include::partial$gen/bibliography.adoc[tags=molter_erlebniswelt_2006]
, bspw. als Aufwärm- oder Stärkungsübung.

Stattdessen können alle Methoden der Beinarbeit, bspw. aus
include::partial$gen/bibliography.adoc[tags=molter_erlebniswelt_2006]
, Kap. 4.3 eingesetzt werden.

Entsprechend dem differenziellen Lehren und Lernen sollen dabei aber:

* Keine Korrekturen erfolgen, weder einzeln noch in die Gruppe.
* Jeweils eine Menge von Varianten vorgegeben werden (Körperposition, Geschwindigkeiten, …)
* Keine Übung ohne Änderung wiederholt werden.
* Spätestens nach wenigen Minuten eine komplett neue Bewegungsaufgabe in die Gruppe gegeben werden (dabei empfiehlt es sich aber auf Zeitgründen, evtl. eingesetzte Trainingsmittel nicht auszutauschen).

Durchgeführte Übungen müssen darauf fokussieren, auch bei den für die Beinarbeit typischen hochgradigen Automatisierung der Bewegungsausführung trotzdem weiter Fehler bei den Lernenden zu provozieren. Diese Fehler äußern sich in der Regel darin, dass Geschwindigkeits- oder Präzisionsvorgaben oder weitere Randbedingungen nicht eingehalten werden können. Diese Fehler müssen für die Lernenden erfahrbar sein, damit eine Korrektur eintreten kann.

Zur Selbstüberprüfung der eigenen Technik sollen den Lernenden gelegentlich spielerische Wettkampf-Formen angeboten werden. Diese sollen auf externe Qualitäten (Geschwindigkeit, erzielte Präzision beim Erreichen einer Position, Treffgenauigkeit aus der Bewegung, …) statt auf interne Qualitäten („schöne Bewegungsausführung“, „tiefe Position“, …).

== Grundlegende Bewegungen

include::partial$techniktraining/koerperbewegungen/beinarbeit/fechtstellung.adoc[leveloffset=+1]

include::partial$techniktraining/koerperbewegungen/beinarbeit/ausfall.adoc[leveloffset=+1]
include::partial$techniktraining/koerperbewegungen/beinarbeit/fleche.adoc[leveloffset=+1]

== Floating Fléche
