== Umsetzungsprinzipien

Die Methodik des differenziellen Lernens ist auf unterschiedlichste Bereiche erfolgreich anwendbar. Das reicht von den bereits erwähnten Studien in verschiedenen Einzel- und Mannschaftssportarten über Ausdauer- und Krafttraining bis hin zum Koordinationstraining cite:[TKFDL].

Die Umsetzung basiert auf dem Prinzip der Variation cite:[BWADLS]:

* Orientierung am individuellen Lösungsbereichs
* Stabilität durch Variabilität/Einmaligkeit
* Parameter-Variation, einschließlich Kontrastbildung im Bereich der „Invarianten“
* Fehler als notwendige Voraussetzung des Lernens
* Selbstoptimierung
* selbstorganisierender, nicht-linearer Lernvorgang

Dabei wird auch der klassische Ansatz der Methodischen Reihen (z.B. nach cite:[LSmMR]) aufgelöst: Im geblockten Ansatz wird jede Übung z.B. 10 Mal hintereinander ausgeführt, bevor zur nächsten fortgeschritten wird. Im systemdynamischen Ansatz wird die Reihenfolge zufällig geändert. Sind in klassisch geblockten Ansatz nur zu Beginn einer neuen Übung größere Anpassungen nötig, variiert dann die Anzahl und Größe der Anpassungen und führt zu einem schnelleren Erfassen und Lernen der Inhalte. Zusätzlich steigt die Abwechslung für die Lernenden und damit die Motivation zur Teilnahme.

Soll ein Bewegungsmuster trainiert werden, dann ist anzustreben, dass möglichst schnell - am Besten von Anfang an - das vollständige Bewegungsmuster trainiert werden soll, auch dann, wenn dieses Vorgehen zunächst sehr hohe Fehlerraten erzeugt. Nach cite:[TKREML] führt eine abschnittsweise Einführung einer komplexen Bewegung zu schlechteren Lern- und Retentionsraten. Es ist aber darauf zu achten, dass Fehler aus der Handlung der Lernenden resultieren und nicht etwa zufällig auftreten, weil nur diese Fehler das Lernen verbessern.

Schon cite:[BBFTMG] verweist darauf, dass das „selbständige Üben“ das Grundverfahren beim Erlernen und Trainineren der (Technik-)Elemente darstellt. Mit differenzieller Lernmethode sollen in den Übungen die Variationen bewusst vergrößert und keine Wiederholungen mit identischen Parametern durchgeführt werden. Variiert werden können z.B. (wieder nach cite:[BWADLS]):

* Bewegungsausführung
** Anfangs-, Endbedingungen
** räumliche Ausführung
** räumlich-zeitliche Ausführung (Geschwindigkeit)
** dynamische Ausführung (Beschleunigung)
** zeitliche Ausführung (Rhythmus)
** Umfang
** Dauer
* Sinneswahrnehmungen (Einschränkungen, Verstärkung)
* Materialien, Geräte
* Untergrund, Gelände
* Rahmenbedingungen, Regeln

Dabei dürfen die Anpassungen bis in den Programmbereich hinein reichen, also die Technik selbst verändern, z.B. den Ausschluss eines Körperteils oder bewusst „falsche“ Technik.

In der Gruppe sollen auch offene Spiel- und Übungsformen und forschendes Lernen eingesetzt werden (z.B. nach cite:[DSSvV]).

Es sollen beim Bewegungslernen hohe Fehlerraten angestrebt werden. Wir streben an, dass über 75% aller Bewegungen fehlerhaft ausgeführt werden, weil nur durch Abweichungen zum gewünschten Verhalten zu einer Anpassung in den Gehirnstrukturen führt. Das bedingt außerdem, dass Abweichungen und deren Konsequenz für die Lernenden sichtbar sein muss.

=== Umsetzung der Variation in der Sportart Fechten

In der Sportart Fechten können alle Parameter variiert werden, solange sie sich innerhalb der vom Reglement erlaubten bewegen und nicht zu vermeidbaren Verletzungsrisiken führen. Bei Variationen außerhalb des Bereichs des Reglements ist darauf zu achten, dass eine prinzipielle Ähnlichkeit erhalten bleibt: Variationen weit außerhalb des möglichen Lösungsbereichs fallen weg.

Prinzipiell bieten sich folgende Variationsmöglichkeiten im Techniktraining an:

. Unterschiedliche Körperpositionen (normal, tief, geduckt, vor-/zurück geneigt, …)
. Unterschiedliche Hand- und Waffenhaltungen (Auslagen, Drehung der Hand, Griffart an der Waffe, Griffstärke, …)
. Unterschiedliche Ausgangs-Bewegungsart (stehend, im Vorrücken, im Zurückweichen, im Sprung, …)
. Unterschiedliche Geschwindigkeiten (langsam, schnell, submaximal, maximal, …)
. Unterschiedliche Beschleunigung (konstant, beschleunigt, verzögert, umkehrend, ...)
. Unterschiedliche Gelenkstellungen (gebeugt, gestreckt, getreckter Arm, angewinkelter Arm, …)
. Unterschiedliche Muskelspannung
. Unterschiedliche Fußstellung
. Unterschiedlicher Rhythmus, Schrittzahl, …

Um eine komplexe Technik zu erlernen, sollen pro Training nicht mehr als 60 Aktionen (jeweils unterschiedliche Variations-Kombinationen) bei 2 bis max. 3 Trainingseinheiten pro Woche absolviert werden. Spätestens dann soll die trainierte Bewegung gewechselt werden. Die Komplexität soll während einer Trainingseinheit gesteigert werden.
