= Technisches Lektionstraining

Lektionstraining im Fechten bezeichnet ein Training, bei dem ein:e Trainer:in mit einzelnen Athlet:innen jeweils separat trainiert.

Nur selten tauchen Formen auf, bei denen mit mehreren Athlet:innen gleichzeitig lektioniert wird.

_Technisches_ Lektionstraining konzentriert sich darauf, der Athlet:in einzelne technische Elemente oder einfache Kombinationen zu vermitteln. Die Zusammensetzung mehrerer Aktionen und der situativ angemessene Einsatz ist Bestandteil des xref:page$agilitaetstraining.adoc[].

Die Auswahl der Techniken, die jeweils trainiert werden sollen, liegt primär bei der Trainer:in. Gerade Jugendlichen und Erwachsenen sollen diese bei der Auswahl einbezogen werden.

Gerade beim Aufbau komplizierterer Techniken (z.B. Quart-Coupé, Wurfstoß Schulter) kommen oft methodische Reihen zum Einsatz, die einzelne Elemente unabhängig voneinander trainieren und erst später kombinieren.

Gemäß der xref:page$grundlagen.adoc#grundlagen-umsetzungsprinzipien[Umsetzungsprinzipien] ist es besser, diesen geblockten Ansatz aufzulösen und die Reihenfolge des Erlernens zufällig zu variieren
include::partial$gen/bibliography.adoc[tag=LSmMR]
.

Zusätzlich ist eine ausreichend hohe Fehlerrate anzustreben, damit die Voraussetzung für neuronale Plastizität gegeben ist. Diese Misserfolgsquote soll zwischen 60% und 80% liegen.

== Zum Umgang mit den Lernenden

Zum Umgang mit der Athlet:in sollen folgende Grundsätze beachtet werden:

* Die Notwendigkeit hoher Fehlerraten sind der Athlet:in vorab zu erläutern, sodass eine Akzeptanz des häufigen Misserfolgs als notwendige Voraussetzung gegeben ist: "Wenn Du etwas zu gut kannst, mache ich die Übung schwerer. Das ist für das Lernen notwendig. Wenn ich es Dir schwerer mache, dann heißt das, dass Du die Übung schon zu gut kannst."

* Ein:e Athlet:in wird nicht getadelt oder kritisiert. Die Rückmeldung über die Effektivität der gelernten Bewegung geschieht immer implizit über die Erfahrung von Erfolg und Misserfolg. Unerwartete Ausführungsvarianten sind durch Bewegungsaufgaben zu infrage zu stellen. Die Athlet:in wird sie korrigieren, wenn sie tatsächlich ineffektiv sind. Ansonsten darf die Variante beibehalten werden.

* Jede erfolgreiche Ausführung muss die Athlet:in sich erarbeiten. In keinem Fall sorgt die Trainer:in dafür, dass eine Aktion erfolgreich ist. Die unverfälschte Rückmeldung effektiver Aktionen ist die Grundlage für das Bewegungslernen.

* Lektionszeit ist Übungszeit. Die Athlet:in soll möglichst durchgehend selbst aktiv sein. Erläuterungen zu Theorie und Hintergründen sind Teil des Taktiktrainings oder können bei Interesse separat erfolgen. Die Methoden "Lernen durch Beobachtung", "Lernen durch Einsicht" und "Lernen durch Bewusstmachen von Bewegung" sind deutlich weniger effizient (siehe xref:page$grundlagen.adoc#grundlagen-klassische-trainingsmethoden[Klassische Trainingsmethoden]).

== Prinzip der Lektionsarbeit

Grundlegend sind technische Lektionen so aufgebaut, dass jeweils ein einzelnes Technik-Element herausgegriffen wird, dass dann in möglichst vielen Variationen ausgeführt wird.

Zur Variation stehen die xref:page$grundlagen.adoc#umsetzungsprinzipien-variabilitaet[Variablen des differenziellen Trainings] und die xref:page$motoriktraining.adoc#koordination-druchbedingungen[Druckbedingungen des Koordinationstrainings] zur Verfügung.

Gemäß der xref:page$grundlagen.adoc#grundlagen-umsetzungsprinzipien[Umsetzungsprinzipien] wird auch bei der Lektionsarbeit eine einzelne Übung (=Kombination aus Aktion und gewählter Variation) niemals wiederholt. Es geht immer mit der nächsten Kombination weiter.

== Beispiele für technische Lektionen

Die Beispiele sind gruppiert nach _Angriff_, _Parade_, _Gegenangriff_ und _Beschäftigung_. Es sei darauf hingewiesen, dass die Unterscheidung der Gruppen im Degenfechten sehr unscharf ist; speziell zwischen _Parade/Riposte_ und _Gegenangriff mit Klingenbeseitigung_.

Wir verwenden die Begriffe wie folgt:

* Die Gruppe _Angriffe_ geht davon aus, dass die Fechter:in eine Aktion zur Erzielung eines Treffers selbst initiiert.
* Die Gruppe _Gegenangriff_ geht davon aus, dass die Trainer:in eine Aktion beginnt, auf die die Fechter:in reagiert in der Absicht, selbst einen Treffer zu erzielen und dabei optional den Gegentreffer vermeidet.
* Die Gruppe _Parade_ geht davon aus, dass die Trainer:in eine Aktion beginnt ud die Fechter:in diesen vereitelt und dabei optional selbst einen Treffer setzt.
* Die Gruppe _Beschäftigung_ geht davon aus, dass die Fechter:in versucht, die gegnerische Initiative zu unterdrücken und dabei optional selbst einen Treffer setzt.

Eine vollständige Lektion kann zwischen 15 Minuten und einer Stunde dauern. Die Dauer soll so gewählt werden, dass die Athlet:in die Konzentration aufrecht erhalten kann.

Wir versuchen, bei einer Lektion mehrere Elemente zu trainieren. Ein Element soll (einschließlich aller trainierten Variationen) nicht länger als fünf Minuten am Stück trainiert werden. Danach soll zu einem anderen Element gewechselt werden. Dadurch soll ein Variationsdruck erzielt werden, der die Voraussetzungen für die Neuroplastizität erhöht.

== Lektionselemente zum Angriff

include::uebungen/technisch/angriff-direkt-beobachtung.adoc[leveloffset=+2]

include::uebungen/technisch/angriff-kavation-als-reaktion.adoc[leveloffset=+2]

== Lektionselemente zum Gegenangriff

include::uebungen/technisch/gegenangriff-meidbewegung.adoc[leveloffset=+2]

== Lektionselemente zur Parade/ Riposte

include::uebungen/technisch/parade-tief-wurfstoss.adoc[leveloffset=+2]

== Lektionselemente zur Beschäftigung


