= Wheelchair fencing training plan
:keywords: exercise
:uebung-group: training plans

ifndef::ownpage[]

xref:page$practices/training-planning/training-plans/90min/2019-20_90-6a.adoc[Only this exercise]

endif::[]

Duration: 90 min

Materials: Long benches or similar

[cols=".^8,.^1"]
|===
a|=== warm up
|*15 min*

a|==== tag

Source:

include::partial$gen/bibliography.adoc[tags=GIFI]

.Description:
* Always four players together
* Three hold onto the slopes and form a triangle.
* One of them must be caught, everyone takes turns
* The fourth player should catch this target. The others try to move in such a way that the target is protected (by rotating!).
* If the target is caught, then the RIGHT becomes the new catcher and the left becomes the new target.
* After one minute at the latest, there will be a change (ANNOUNCEMENT!).

//-

.Ensure that:
* The catcher only runs around the outside, not through the middle (and does not reach through): Risk of injury! +
* people not to overexert themselves. Especially for groups with people of varying strengths/speeds
|3 times 3 minutes

a|==== Drinking
|5 min

a|=== mask relay

Intensive warming up of the upper body and arm muscles, which are particularly strained during wheelchair fencing.

Teams of roughly equal strength, each with 4 to 5 people and one mask each

The mask is passed on to the next person in line. The last one runs to the front and starts again there (that's how it works).

The team that is furthest ahead after minutes starts.

* Sideways transfer
* Throw up over your head
|*10 min*

a|=== Drink, change clothes, set up
|*15 min*

a|=== wheelchair fencing

* With benches to sit down on
* Detectors next to the boxes
* Set the distance correctly: hold the weapon in a straight line up to your opponent's elbow (inside).
* If the fencers are of different heights, the shorter one decides the distance.
* Five hits each, approx. 5 people per round
* Always with a referee

*Parallel: Individual lessons*
|*35 min*

a|=== Dismantling
|10 min
|===