= Fang Die Socke

Zwei Fechtende stehen sich gegenüber. Beide haben eine Fechtsocke über ihrem Waffenarm hängen, direkt beim Ellenbogen. +

*Keine Waffen, keine Schutzausrüstung*

*Das Ziel*

1. Klau die Socke des Gegners, bevor er deine erwischt (5 Punkte)
2. Sorge dafür, dass Deine Socke nicht zu Boden fällt (1 Punkt für den Gegner)

_(ehrlich gesagt müssen wir eigentlich nie zählen)_

*Aufbau-Varianten*

1. Auf dicken Weichboden-Matten
2. Nutze ein Feld aus 2x2 dünnen Turnmatten. Du darfst nur klauen, wenn Deine Gegnerin und die dieselbe Matte berühren.
3. Verteile Bodenmarkierungen auf der Bahn (Gummikacheln, Reifen, o.ä.): Klauen ist nur erlaubt, wenn man eine davon berührt.
4. Spiele laute Musik dabei ab (bricht Rhythmus und akustische Orientierung)

*Spiel-Varianten*

1. Die Socke liegt über der Schulter
2. Zusätzlich eine Poolnudel in der Waffenhand. Geklaut werden darf nur mit der freien Hand.
3. Spanne ein Theraband um die Knöchel. Klauen darf nur, wer sein Theraband gespannt hat.
4. Spanne ein Theraband knapp über die Knie.
5. Spiele mit 3 gegen 3 auf einem Viertel Volleyballfeld (4 Runden à 20 Sekunden)
6. Coach und Helfer ziehen ein langes Seil auf dem Boden ODER in Kopfhöhe durch die Bahnen. Die Athleten dürfen es nicht berühren!
7. Nutze eine Linienmarkierung. Die Athletinnen dürfen sich nur auf der Linie bewegen.
8. Verwende Gewichtsmanschetten (je nach Alter 200 g bis 2 kg)
9. Athletinnen klemmen einen Tennisball mit dem Kinn gegen die Brust
10. Die unbewaffnete Hand darf nicht benutzt werden. Sie klammert sich deswegen am Oberschenkel fest.
11. Während des Spiels singen beide Athleten ihr Lieblingslied laut um die Wette!

*Warum das funktioniert*

Indem wir komplexe Fechthandlungen in spielerische Constraints verpacken, umgehen wir die ineffektive „Paralysis by Analysis“ und aktivieren die natürliche Selbstorganisation des Körpers. Anstatt Bewegungen zu diktieren, schaffen wir gezielte Probleme, die der Athlet durch  Perception-Action-Coupling und kreative Lösungswege selbst löst.

So entsteht technisches Können nicht durch das Auswendiglernen von Regeln, sondern als unmittelbare, körperliche Antwort auf die Herausforderungen im Degen-„Bossfight“.
