= Die Fechtstellung

Die Position, in der sich Fechter:innen in Ruheposition befinden, stellt bereits eine individuelle Lösung der Anforderungen der Gefechtssituation dar.

Sie ermöglicht es speziell, ohne Auftaktbewegung hohe horizontale Kraft auf den Boden in möglichst viele unterschiedliche Richtungen ausüben zu können. Dabei sind mögliche horizontale Beschleunigungen nach vorne und nach hinten von besonderem Interesse.

Zusätzlich soll bereits aus dem Stand eine große Treffer-Reichweite erzielt werden können, um vorgelagerte Trefflächen ohne Fußbewegung angreifen zu können und bei überraschenden Angriffen bessere Chancen auf einen Treffer mit Arrêt besteht.

Für Ausweichbewegungen ist eine hohe Hüftbeweglichkeit von Vorteil.

Im Vergleich zur traditionellen Fechtstellung, bspw. in
include::partial$gen/bibliography.adoc[tag=ErlFe]
, Kap 4.1, sind im modernen Degenfechten Anpassungen sichtbar.

.Moderne Fechtstellung am Beispiel von https://en.wikipedia.org/wiki/Choi_In-jeong[Choi In-jeong]
image::technik-fechtstellung.svg[Embedded,80%]

Die wichtigsten Anpassungen, die bei vielen Fechtern im höheren Leistungsbereich sichtbar sind:

* Der Fußabstand wird in vielen Fällen deutlich vergrößert. Zweieinhalb bis drei Fußlängen sind hier keine Seltenheit. Dieser Abstand verbessert den Winkel, mit dem der hintere Fuß Kraft auf den Boden überträgt. In Abhängigkeit vom Reibungskoeffizient zwischen Schuhsohle und Metallbahn liegt der optimale Winkel bei etwa 42°. Das ist in normalen Stellungen nicht ganz zu erreichen, sodass hier meist gilt: je mehr, desto besser.
* Speziell beim hinteren Fuß wird häufig die Ferse vom Boden gehoben. Bei großen Bodenwinkeln ist eine entspannte Haltung anders auch nicht möglich, weil das Ziel ist, die Wadenmuskeln im optimalen Arbeitsbereich zu halten.
* Der Oberkörper wird nach vorne geneigt, so dass der Körperschwerpunkt in einer Linie mit dem hinteren Bein liegt. Dadurch werden beim Beschleunigen vorwärts Torsionskräfte vermieden und eine exakte Spitzenführung vereinfacht. Zusätzlich wird der Körperschwerpunkt ein Stück weit nach vorne verschoben, um für Rückwärtsbewegungen die nötige Reibung auf dem vorderen Fuß erzeugen zu können.
* Der vordere Fuß wird nach vorne verschoben. Der dadurch entstehende Winkel zwischen Bein und Boden verbessert die Möglichkeit zur Bschleunigung nach hinten.
* Der hintere Arm wird normalerweise neben dem Körper geführt und für die Kompensation von Rotationsbewegungen des Oberkörpers aktiv genutzt.
* Die hintere Schulter wird oft weiter nach vorne geführt. Dadurch wird bereits im Stand eine höhere Hüftbeweglichkeit gefördert. Bei Angriffen kann die Schulter schnell beim Arrêt aus der Linie gedreht werden.
* Der vordere Arm wird stärker angewinkelt, oft in einem Winkel von 90°. Da die explosive Armstreckung in unter 100ms erfolgt
include::partial$gen/bibliography.adoc[tag=AREKinSP]
  und die Muskulator in stärkerer Kontraktion höhere Kräfte erreicht, kommt auch aus dieser Position ein Treffer nahezu gleichzeitig auf. Es lässt sich dadurch ohne Nachteile eine höhere Manövrierfähigkeit erreichen und die Hand ist vor Angriffen besser geschützt.
* Mit der Wahl einer solchen Fechtstellung erfolgt meistens auch eine Umstellung der Beinarbeit. Die Gewichtsverteilung erlaubt keine einfachen Schritte mehr. Entweder wird die Fechtstellung für einfache Schritte aufgegeben (für Situationen ohne Druck in überweiter Mensur) oder es werden ausschließlich Sprünge durchgeführt, die dann meistens aus den Fußgelenken erfolgen.

Es ist anzumerken, dass die genaue Fechtstellung sehr stark von der anwendenden Fechter:in abhängt und ein großer Varianzbereich sichtbar ist. In jedem Leistungsbereich sollen regelmäßig Varianten angeboten werden, um die Variabilität zu erhöhen und individuelle Lösungen zu fördern.