= Training der Körperbewegungen im Fechtsport

Für das Training von Körperhaltung und Körperbewegung im Fechtsport ergeben sich eine Reihe von Problemen. Zum einen fällt auf, dass bereits die Grundstellung, wie sie klassisch bspw. in
include::partial$gen/bibliography.adoc[tag=BBFTD]
gelehrt wird, bei der Auswertung von Top-Athleten nicht vorzufinden ist.

Verschiedene „Stile“ resultieren bei allen Fechtern in sehr unterschiedlichen Lösungen bezüglich Kraft, Geschwindigkeit, Beschleunigung, Haltung und Energieaufwand
include::partial$gen/bibliography.adoc[tag=SFIPIP]
. Diese sind nicht nur abhängig von Anthropometrie und Trainingsstand, sondern immer auch von konkreten fechterischen Situationen, die einer angepassten Lösung bedürfen.

Besonders für Heranwachsende ist das Bewegungstraining einer Herausforderung, da sich ständig änderne Hebel, Proportionen und Kraftverhältnisse eine ständige Anpassung der notwendigen Technik bedingen.

Ziel des Trainings der Körperbewegungen muss deswegen immer sein, dem Athleten Stabilität bei der Anpassung und Adaption seiner Bewegungen an neue Situationen zu ermöglichen.

== Beinarbeit

Klassische Beinarbeit „auf Ansage“ und ohne Variantenvorgaben, gezielt auf die Einhaltung einer Zieltechnik, erzielt schon nach kürzester Zeit keinen technischen Lerneffekt mehr und sollte höchstens untergeordnet eingesetzt werden
include::partial$gen/bibliography.adoc[tag=ErlFe]
, bspw. als Aufwärm- oder Stärkungsübung.

Stattdessen können alle Methoden der Beinarbeit, bspw. aus
include::partial$gen/bibliography.adoc[tag=ErlFe]
, Kap. 4.3 eingesetzt werden.

Entsprechend dem differenziellen Lehren und Lernen sollen dabei aber:

* Keine Korrekturen erfolgen, weder einzeln noch in die Gruppe.
* Jeweils eine Menge von Varianten vorgegeben werden (Körperposition, Geschwindigkeiten, …)
* Keine Übung ohne Änderung wiederholt werden.
* Spätestens nach wenigen Minuten eine komplett neue Bewegungsaufgabe in die Gruppe gegeben werden (dabei empfiehlt es sich aber auf Zeitgründen, evtl. eingesetzte Trainingsmittel nicht auszutauschen).

Durchgeführte Übungen müssen darauf fokussieren, auch bei den für die Beinarbeit typischen hochgradigen Automatisierung der Bewegungsausführung trotzdem weiter Fehler bei den Lernenden zu provozieren. Diese Fehler äußern sich in der Regel darin, dass Geschwindigkeits- oder Präzisionsvorgaben oder weitere Randbedingungen nicht eingehalten werden können. Diese Fehler müssen für die Lernenden erfahrbar sein, damit eine Korrektur eintreten kann.

Zur Selbstüberprüfung der eigenen Technik sollen den Lernenden gelegentlich spielerische Wettkampf-Formen angeboten werden. Diese sollen auf externe Qualitäten (Geschwindigkeit, erzielte Präzision beim Erreichen einer Position, Treffgenauigkeit aus der Bewegung, …) statt auf interne Qualitäten („schöne Bewegungsausführung“, „tiefe Position“, …).

=== Einfache Schritte und Sprünge

=== Der Ausfall

Als eines der grundlegenden Elemente der fechterischen Bewegungen kommt dem Ausfall eine große Bedeutung zu. Er wird in unzähligen Veröffentlichungen im Details beschrieben, bspw. In
include::partial$gen/bibliography.adoc[tag=ErlFe]
. Die tatsächlich von Sportlern durchgeführte Bewegung weicht von der Beschreibung nahezu immer ab. Das betrifft sowohl die Ausgangsposition, bei der deutlich mehr Gewicht auf dem vorderen Fuß lastet
include::partial$gen/bibliography.adoc[tag=KDSFL]
, als auch die Fussbewegung, bei der in allen beobachteten Fällen die vordere Ferse zuerst den Boden verlässt
include::partial$gen/bibliography.adoc[tag=KALFS]
.

Der zu trainierende Lösungsbereich könnte so eingeschränkt werden:

* Ausgangspunkt ist eine Fechtstellung im Rahmen der gültigen Parameter oder einer Position, die aus regelkonformen Aktionen erreicht werden kann.
* Ziel ist es, mit der Spitze der eigenen Waffe einen entfernten Punkt möglichst schnell zu treffen.
* Dabei soll der vordere Fuß explosionsartig weiter nach vorne gebracht werden.
* Dabei soll kein Überkreuzen der Füße erfolgen und die Bewegung soll danach beendet sein (Abgrenzung zum Fléche und zum Säbel-spezifischen „Flunge“).

Alle anderen Parameter sollen teil der zu trainierenden Variationen sein. Das betrifft insbesondere, aber nicht ausschließlich: die Reihenfolge der Arm- und Beinbewegung; die Beschleunigung/Verzögerung bei der Ausführung; die Fußstellung vor, während und nach der Ausführung; die Arm- und Handlage während der Ausführung. Dabei ist besonders bei der Vorgabe der Fußstellung darauf zu achten, dass Verletzungs-treibende Vorgaben unterbleiben (bspw. darf das Knie nicht nach innen fallen).

Der Ausfall kann auch mit Partnerübung trainiert werden. Dort ist auch die Reaktion auf gegnerische Störungen während des Ausfalls trainierbar.

=== Fléche

== Meidbewegungen

== Körpertäuschungen

