= Training der Körperbewegungen im Fechtsport

Wenn es um das Training von Körperhaltung und Beinarbeit geht, stoßen wir in der klassischen Fechtlehre schnell auf ein faszinierendes Phänomen: Schlag mal ein traditionelles Lehrbuch wie beispielsweise
include::partial$gen/bibliography.adoc[tags=barth_fechttraining_2005]
auf und betrachte die dort oft gepredigte, winkelgenaue Grundstellung. Wenn Du dann den Blick hebst und Dir Weltklasse-Fechterinnen und -Fechter im Wettkampf ansiehst, wirst Du feststellen: Diese erstarrte Lehrbuch-Pose existiert in der freien Wildbahn praktisch nicht.

Stattdessen sehen wir auf der Planche unzählige individuelle „Stile“. Jeder Athlet und jede Athletin (ob Fußgänger oder im Rollstuhl) findet höchst unterschiedliche, aber funktionale Lösungen, wenn es um Kraft, Geschwindigkeit, Beschleunigung, Haltung und Energieaufwand geht
include::partial$gen/bibliography.adoc[tags=roi_science_2008]
.

Das ist kein Mangel an Disziplin, sondern das Grundprinzip der ökologischen Dynamik! Wie sich jemand bewegt, hängt eben nicht von einer abstrakten Idealform ab, sondern von den eigenen körperlichen Voraussetzungen (Anthropometrie), dem Trainingsstand und vor allem von der konkreten, sich ständig wandelnden Situation im Gefecht, die in Sekundenbruchteilen nach einer angepassten Lösung verlangt.

Besonders im Nachwuchsbereich wird das Festhalten an einer „perfekten“ Technik vollends absurd. Heranwachsende befinden sich in einem permanenten Umbau: Hebel, Körperproportionen und Kraftverhältnisse verändern sich durch Wachstumsschübe quasi über Nacht. Eine Bewegungslösung, die heute noch hervorragend funktioniert, muss morgen vielleicht schon wieder völlig neu justiert werden.

Das oberste Ziel beim Training der Körperbewegungen darf deshalb niemals das sture Einschleifen einer normierten Schablone sein. Unser Job als Coach ist es vielmehr, den Athleten und Athletinnen eine hohe funktionale Stabilität zu vermitteln. Wir wollen ihnen eine Umgebung schaffen, in der sie lernen, ihre Bewegungen jederzeit fließend, robust und kreativ an neue, unvorhersehbare Situationen und ihren eigenen Körper anzupassen.

include::partial$techniktraining/koerperbewegungen/beinarbeit.adoc[leveloffset=+1]

== Meidbewegungen

== Körpertäuschungen

