= Stoß- und Treffbewegungen

Die maßgeblichen Einflussfaktoren, die über erfolgreiches Treffen gewünschter Zielregionen entscheiden, sind bislang größtenteils unerforscht. Es gibt nur wenige durch Studien gesicherte Ergebnisse.

Beispielsweise ist bekannt, dass die Technik für Würfe nicht mit denen der Handführung bei Treffbewegungen im Fechten korrelieren
include::partial$gen/bibliography.adoc[tag=KCLFEF]
. Weiter ist bekannt, dass selbst während eines Ausfalls oder Fléche die Zeit bis zum Aufkommen des Treffers (500-600ms, aus
include::partial$gen/bibliography.adoc[tag=FLOFT]
) ausreicht, um das Ziel zu erfolgreich zu ändern (200ms, aus
include::partial$gen/bibliography.adoc[tag=ACOAEF]
).

== Zur Regel "Arm vor Bein"

Mit der Regel "Arm vor Bein" wird ausgedrückt, dass bei kombinierten Treffbewegungen, die Armstreckung und Körperbewegung beinhalten, zunächst die Armstreckung erfolgt, bevor die Beinbewegung begonnen wird
include::partial$gen/bibliography.adoc[tag=GTHOF]
. In der abgeschwächten Form wird die Beinbewegung schon kurz vor Abschluss der Armbewegung begonnen
include::partial$gen/bibliography.adoc[tag=AKonDFB]
.

Eine Auswertung aller offensiven Treffer der Finalrunde des Weltcups in Doha 2024 ergab, dass kein einziger Angriff, der Arm- und Beinbewegung beinhaltete, auf diese Weise durchgeführt wurde. Angriffe erforderten entweder nur eine Armbewegung oder sie wurden mit dem Bein eingeleitet.

Kein Angriff, der nur eine Armstreckung benötigte, wurde danach direkt fortgesetzt, sondern stets der Arm zurückgezogen.

Die notwendigen 500-600ms, die für einen Angriff mit Ausfall oder Fléche notwendig sind, sind ausreichend für gleich mehrere Fechtaktionen. Deswegen ist es wichtig, den Waffenarm so lange wie möglich vor Gegenangriffen zu schützen und die Manövrierfähigkeit möglichst lange aufrechtzuerhalten. Beides benötigt einen mindestens halb angewinkelten Arm, wie in
include::partial$gen/bibliography.adoc[tag=ErlFe]
(zur Fechtstellung) erläutert.

Es ist angeraten, erst im Moment des Auftreffens der Spitze die maximale Armstreckung zu erreichen. Da der einfache Ausfall etwa 500ms benötigt, die explosive Armstreckung dagegen weniger als 100ms
include::partial$gen/bibliography.adoc[tag=AREKinSP]
, sollte der Arm erst während der Angriffsbewegung gestreckt werden.

== Training der Stoß- und Treffbewegung

Die reine Stoß- und Treffbewegung lässt sich durch variable Stoßübungen trainieren. Gerade dabei ist die Variabilität einer der wichtigsten Faktoren, denn Treffbewegungen müssen aus unterschiedlichsten Situationen und Körper-/Handhaltungen sicher und schnell erfolgen können.

Für Stoßübungen bietet es sich an, die Übungen in kurzen Blöcken durchzuführen: Es werden bezüglich einer Größe über mehrere Übungen mehrere Variationen ausgeführt (z.B. in Folge sechs verschiedene Treffer-Flächen; vier verschiedene Ausgangs-Klingenlagen). Dazu wird jeweils eine Kombination aus Variationen hineingegeben (z.B. Ausführung mit Schritt vor, Treffbewegung verlangsamend und ein Auge geschlossen).

Als Hilfsmittel können z.B. dienen:

* Markierungen auf dem Boden, mit dem unterschiedliche Fußpositionen erwürfelt werden können
* Unterschiedliche „Waffen“, z.B. Rohre, Holzstecken, Schlauchstücke
* bewegliche Ziele, z.B. schwingende Bälle, Stoß auf Tischtennisbälle, die in ein Tor befördert werden

Eine Durchführung auf Zeit oder auf die meisten Treffer pro Versuch in Kleingruppen hat sich bewährt.

Um wechselnde Ziele vorzugeben, können diese vorgeplant werden. Alternativ werden sie angezeigt, z.B. mittels Fencing Hit Target oder Laserpointer.

Klingenaktionen können ebenfalls geübt werden, indem in Kleingruppen Gegner neben das Ziel postiert werden. Ein Stoßtraining mit Person als Ziel hat sich dagegen nicht bewährt, da die Abneigung, ggf. schmerzhaft zu treffen oder getroffen zu werden, kaum konzentriertes Training ermöglicht.

include::partial$techniktraining/techniktraining-treffbewegung-einheit.adoc[leveloffset=+1]
