[[grundlagen-klassische-trainingsmethoden]]
== Klassische Trainingsmethoden

Grundlage für traditionelles Lehren und Lernen in Verein und Schule sind drei Modellarten: (1) Lernmodelle, (2) Lehrmodelle, (3) Bewegungsmodelle.

Wesentliche Lernmodelle sind nach
include::partial$gen/bibliography.adoc[tag=LuGed]

[loweralpha]
. Lernen durch Kontiguität, bzw. klassische Konditionierung nach Pawlow und Guthrie.
. Lernen durch Verstärkung/ operante Konditionierung nach Thorndike, Hüll, Skinner
. Lernen durch Beobachtung
include::partial$gen/bibliography.adoc[tag=SFTA]
. Lernen durch Einsicht, Bewusstmachen von Bewegung
include::partial$gen/bibliography.adoc[tag=IaA]

Wesentliche Lehrmethoden sind nach
include::partial$gen/bibliography.adoc[tag=AMdL]
[loweralpha]
. Methodische Reihen (motorische, konditionelle, Spielreihen)
. Induktive – Deduktive Lehrkonzepte mit analytischen/synthetischen Realisierungsansätzen

Grundlegende Bewegungsmodelle sind nach
include::partial$gen/bibliography.adoc[tag=SDLL]

[loweralpha]
. Open-Loop-Modell nach
include::partial$gen/bibliography.adoc[tag=AMAEM]
. Closed-Loop-Modell nach
include::partial$gen/bibliography.adoc[tag=CLTML]
. schematheoretisches Modell nach
include::partial$gen/bibliography.adoc[tag=STDMSL]
und
include::partial$gen/bibliography.adoc[tag=WVKF]

== Probleme und Widersprüche der klassischen Trainingslehre

In den meisten uns bekannten Vereinen wird normalerweise nicht nach einem festen Modell gelehrt, sondern es kommt zu einer Vermischung. Intuitiv und auch mit Erfolg geben Trainer:innen in Anlehnung an das Lernen am Modell Ziel-Techniken vor und versuchen ihre SchülerInnen mit bedingter und operanter Konditionierung möglichst nahe an das eigene oder übernommene Technik-Leitbild anzunähern.

Auch explorative Methoden ("Versuch und Irrtum") werden bisweilen als Methode eingesetzt. Allzu häufig aber mit dem Ziel, die erwartete Zieltechnik möge nun endlich gefunden und eingesetzt werden. Schüler:innen finden zwar gelegentlich eigene Techniken, die eventuell sogar für ihre Voraussetzungen besser geeignet sind; diese werden aber oft als Irrtum ignoriert.

Dabei ist die vorgegebene Ideal-/Zieltechnik häufig problematisch: sie ist manchmal veraltet, oft in sich widersprüchlich und in jedem Fall nicht an die Individualität der SchülerInnen angepasst. Dennoch sollen die SchülerInnen sich nach dem Prinzip der Übereinstimmung
include::partial$gen/bibliography.adoc[tag=SOTP]
)
iterativ den "korrekten" Lösungen annähern, die mit hoher Wiederholungszahl eingeschlossen werden sollen
include::partial$gen/bibliography.adoc[tag=HaTra]
.

Zu beachten ist, dass innovative Neuerungen im Sport normalerweise erfolgen, wenn sich Trainer und Athleten nicht daran orientieren, sondern Technik und Taktik in einem neuen Umfeld neu denken oder neu erproben.

Die Problem mit Ideal-/Zieltechniken ist unter anderem die Nichtwiederholbarkeit identischer Bewegungen
include::partial$gen/bibliography.adoc[tag=MoVaDQO]
: selbst die besten Athleten sind nicht in der Lage, sogar einfache Bewegungen exakt identisch auszuführen.

Das Lernen einer Bewegungsfertigkeit bedeutet im Kern immer, dass eine Veränderung in der Steuerung der Muskulatur notwendig ist, die im Gehirn vorgenommen wird und an mindestens einer der Stellen erstes Motorneuron (Upper Motor Neuron, UMN), zentraler Rhythmusgenerator (Central Pattern Generator, CPG) oder unteres Motorneuron (Lower Motor Neuron, LMN) eine Veränderung bewirkt. Diese Änderung ist bereits das erfolgte Lernen.

Inzwischen ist gut erforscht, wie diese neuroplastischen Änderungen zustande kommen: Fehler. Ein Lernprozess besteht immer darauf, dass Lernende einen Fehler begehen, der über Feedback zu Anpassungen an der plastischen Struktur des Gehirns führt. Um es deutlich zu sagen: Ohne Fehler ist Lernen unmöglich
include::partial$gen/bibliography.adoc[tag=LFEr]
.

Entsprechend gibt es neuere Lehr- und Lernmethoden, die Variabilität ins Zentrum stellen. Beispiele sind der systemdynamische Ansatz (Selbstorganisation nach
include::partial$gen/bibliography.adoc[tag=MPTHHM]
) und die Selbststabilisierung nach
include::partial$gen/bibliography.adoc[tag=SNANF]
. In beiden Fällen sind Fluktuationen Bestandteil der Theorie.

Weiteres Problem ist die Kopplung der Bewegung an das ausführende System, also die Individualität der Bewegungsausführung.

In der Sportpraxis wird zwar immer wieder gesagt, dass Individualität als Abweichung von der Norm akzeptiert werden soll, konkret bedarf es aber der Intuition erfolgreicher Trainer und Athleten, um diese Toleranz auch umzusetzen.
