= Partnerübung: Die Torrero-Falle

*Aufbau*:

Hole einen *Kasten*, stelle ihn *direkt neben* die Fechtbahn auf Höhe der *rechten Startlinie* (gegenüber des Melders).

Nimm das *Oberteil* (mit dem Leder) ab und *lehne es* vorne gegen den Kasten, so dass es in *Richtung der anderen Startlinie* zeigt.

*Ablauf*

1. Stelle die Verteidigerin genau *neben den Kastendeckel*
2. Die Angreiferin startet *in fünf Metern Entfernung*
3. Die Verteidigerin *ruft "LOS GEHTS"*. +
 Ab dann hat die Angreiferin *5 Sekunden Zeit*, um einen Treffer zu setzen. +
 Zielvorgabe: *Brust* (innen/oben)
4. Aufgabe für die Verteidigerin: +
  Sorge dafür, dass die Angreiferin *statt Dir das Kasten-Oberteil* trifft!
5. Und wenn Du kannst, lieber Verteidigerin: +
  Versuche danach *selbst zu treffen!*

*Varienten*

Jede Wiederholung soll anders sein:

* Verteidiger-Position: Mal aufrecht, mal tief in der Hocke, mal halb hoch!
* Verteidiger-Start: Mal neben dem Kasten, mal etwas davor, mal etwas dahinter
* Angreifering: Mal gleich schnell, mal beschleunigen, mal ein kurzer Stopp vor dem Treffen

*Das gibt es zu entdecken:*

* Die Techniken, mit denen man die Innenseite verteidigt: die Quart, die Prim, die Septim (und alles dazwischen)
* Den Unterschied zwischen Schlag-Parade und Bindungsparade
* Das Timing, diese Aktionen zum richtigen Zeitpunkt zu machen, statt zu spät oder zu früh.