== Training motorischer Fähigkeiten
:stem:

Motorische Fähigkeiten sind die Grundlage, auf der das spezifische Fechttraining aufsetzt:

* Ausdauer
* Schnelligkeit
* (Maximal-) Kraft
* Koordination
* Beweglichkeit

Diese motorischen Fähigkeiten sind generell für alle sportlichen Tätigkeiten relevant. Hier ist das Ziel in erster Linie, die Fähigkeiten so zu trainieren, wie sie für den Fechtsport notwendig sind.

Diese Fähigkeiten lassen sich jeweils separat trainieren. Allerdings steht in den meisten Trainingsplänen nicht genug Zeit dafür zur Verfügung, so dass das Training entweder separat durch die Athlet:innen erfolgt oder in das reguläre Training integriert werden muss. Dabei empfiehlt es sich, kombinierte Übungen anzubieten, in denen mehrere motorische Fähigkeiten gleichzeitig trainiert werden können.

=== Motorische Anforderungen des Sportfechtens

Das Sportfechten ist in seiner Belastungsstruktur mit anderen olypmischen Kampfsportarten vergleichbar: Ähnlich wie das Taekwondo liegt der Schwerpunkt auf kurzen Runden hochintensiver Belastung. Neben technischen Anforderungen liegt der Schwerpunkt im anaeroben und neuromuskulären Bereich.

Ähnlich zum Taekwondo lässt sich auch im Sportfechten die maximale aerobe Kapazität auf 60-65 stem:[(ml * kg) / (min)] schätzen.

Grundlegend für hochintensive Belastungen ist eine große aerobe Kapazität (siehe cite:[HPNRHP]), und dabei insbesondere die Herzminutenleistung. Das trifft insbesondere auf Athlet:innen mit bereits hoher VO~2~max zu (siehe cite:[BoVO2].

=== Training der Ausdauerfähigkeiten

Um effizient Ausdauer aufzubauen, ist das Intervalltraining der kontinuierlichen Methode überlegen. Dieselben Leistungssteigerungen werden mit geringerem Zeiteinsatz erzielt (z.B. cite:[ESECIT]).

Das betrifft nicht nur die maximale Sauerstoffaufnahme (VO~2~ max), sondern auch die anaerobe Kapazität. Nach cite:[EMEHIIT] kann durch vier Minuten Hochintensitäts-Intervall Training die VO~2~ max genauso gut verbessert werden wie durch 60 Minuten kontinuierliches Training.

Für das körperliche Training übernehmen wir die Definitionen aus cite:[HICCA(8)]:

* Sprint Interval Training (*SIT*): <30sec maximale Belastung (RPE 10/10), z.B. 30sec maximaler Sprint
* Speed Endurance Training (*SET*): 30-60sec bei https://www.crossfitwiesbaden.com/blog/rpe-training-was-bedeutet-das[RPE] 9/10, z.B: 8x 30sec mit 3min Pause
* Muscle Buffer Training (*BUF*): Belastung mit Resultat von 8-10 stem:[(mmol) / l], bei RPE 8/10, z.B. 6x 2min mit 3min Pause
* High-Intensitive Interval Training (*HIIT*): Intervalle von 2-20min bei RPE 9/10, 90% maximale Herzfrequenz oder 90-95% VO~2~max, z.B. 4x 8min mit 2min Pause

Die Übergänge zwischen den Trainingsarten sind dabei allerdings fließend.

include::motorisch-ausdauer-hiit.adoc[leveloffset=+3]

include::motorisch-ausdauer-hiit-sit.adoc[leveloffset=+3]

=== Maximalkrafttraining

=== Schnelligkeitstraining

=== Koordinationstraining

Koordination bezeichnet nach cite:[KFuKiS] das geordnete Zusammenwirken von verschiedenen Teilen und Prozessen eines Systems auf ein intendiertes Ziel hin.

Der wissenschaftliche Stand zu koordinativen Fertigkeiten ist derzeit lückenhaft. Es bestehen Forschungslücken und empirisch verifizierte alternative Ansätze cite:[KFuKiS].

Dennoch sind einige koordinative Übungsformen sinnvoll und zeigen gute Resultate.

==== Grundlagen des Koordinationstrainings

Die separate Betrachtung der Koordinationsfähigkeiten ist deshalb problematisch, weil sie nicht direkt beobachtbare, hypothetische Konstrukte sind (cite:[RfBDM]) und immer auf ein spezifisches Gefüge aus mehreren Fähigkeiten unterschiedlicher Gewichtung zurückgegriffen wird cite:[WkFuB].

Die Tragfähigkeit des Ansatzes der koordinativen Fähigkeiten wird zunehmend infrage gestellt. Das betrifft besonders das Konzept allgemeiner, übergreifender Koordinationsfähigkeiten. Die Erkenntnisse sprechen eher für eine hohe Fertigkeitsspezifität: Es besteht ein hoher Trainingseffekt auf Leistungen, die Teil des Trainings sind, aber die Effekte lassen sich kaum auf andere Aufgaben übertragen (siehe z.B. cite:[RbSBM] und cite:[HMSSvSe]).

Dennoch wird oft allgemeines Koordinationstraining für sinnvoll erachtet mit den Zielen, außersportliche Handlungskompetenz zu erhalten, Trainingsmonotonie entgegenzuwirken und Handlungssicherheit in Problemsituationen zu erhalten.

Als Anteile am Training werden in cite:[SSlTo] z.B. 5% für algemeines und 10-15% für sportartspezifisches Koordinationstraining genannt.

In cite:[KFuKiS] wird dargestellt, dass das Training allgemeiner Koordinationsfähigkeiten und fertigkeitsbezogenes Techniktraining die beiden Pole des selben Kontinuums sind. Techniktraining ist somit immer auch sportartspezifisches Koordinationstraining cite:[OMBGTwl].

Die Haupttrainingsmethode im fähigkeitskonzeptionellen Koordinationstraining ist das variable Üben cite:[WkFuB].

Die dort dargestellten Variationsmethoden des programm-, parameter- und bedingungsvariablen Übens zeigen eine deutliche Ähnlichkeit zum differenziellen Lernen.

==== Spezifisches Koordinationstraining

Es gilt die Maxime, dass die koordinativen Anforderungen im Training immer höher sein müssen als bei der späteren Reproduktion. Also schwierigere Übungen mit größerer Handlungsdichte als in der Realsituation.

Für das Sportfechten bieten sich als Grundlage die normalen technischen Elemente an, die in Spielformen und Partnerübungen eingesetzt werden. Hinzu kommen dann immer variable Druckbedingungen, die für die Ausbildung der gewünschten, koordinativen Fähigkeiten sorgen.

Es gilt nach cite:[WkFuB]:

*Koordinationstraining = beherrschte Fähigkeit + sensorische Vielfalt + Druchbedingungen*

|====
|Druckbedingung|Dimensionen|Übungsbeispiel

|Zeit
a|* verfügbare Bewegungszeit
* zu erreichende Geschwindigkeit
a|* Parade-Riposte mit maximalem Tempo
* Auswahlreaktion unter Zeitdruck

|Präzision
a|* Körperposition
* Körperlage
* Handlage
* Klingenlage
* Spitzenposition
a|* Zielvorgaben beim Treffen
* Beinarbeit auf einer Langbank
* Sperrstöße mit Vorgabe des Berührungspunkts

|Komplexität
a|* simultane Bewegungsteile
* sukzessive Bewegungsteile
* einbezogene Körperteile
a|* Fechten auf einer Hindernisbahn
* Imitiation von Gefechtsphrasen
* Gefecht gegen mehrere Gegner

|Situation
a|* Variabilität der Umgebung
* Komplexität der Umgebung
* Variabilität der Situation
* Komplexität der Situation
a|* Auswahlübungen mit mehreren Optionen
* Übungsgefechte mit schnell wechselnden Gegnern

|Belastung
a|* physische Belastung
* psychische Belastung
a|* Übung nach konditioneller Vorbelastung
* gleichzeitiges Lösen einer Kopfrechenaufgabe

|====

==== Neuroathletik-Training

Die Neuroathletik beschäftigt sich mit Prozessen des Gehirns und der Nerven bei der Entwicklung der Bewegungsprogramme, bevor es zu einer Handlung kommt.

Schwerpunkt ist die Schulung der Wahrnehmung

* des visuellen Systems (Sehen)
* des vestibulären Systems (Gleichgewicht)
* und des propriozeptiven Systems (Eigenwahrnehmung).

Grundlage ist, dass die Qualität der Wahrnehmung und der Verarbeitung im Gehirn ausschlaggebend dafür ist, ob das Gesamtsystem Athlet die maximale Leistung zielgerichtet abrufen kann. Bei Problemen in der Wahrnehmung reagiert das Gehirn damit, die verfügbare Leistung zu reduzieren, um Verletzungsrisiken auszuschließen.

Diese Verarbeitung läßt sich bei allen Athlet:innen optimieren. Oft lassen sich Defizite in diesem Bereich mit bloßem Auge identifizieren:

* Die Bewegungen erscheinen ungelenk.
* Aktionen werden zögerlich und vorsichtig durchgeführt.
* Bewegungen erscheinen inkonsequent, werden unterbrochen oder abgebrochen.
* Aktionen erfolgen vorsichtig, den Athlet:innen scheint das Vertrauen in die eigenen Fähigkeiten zu fehlen.
* die Athlet:innen wenden sich ab (z.B. bei Paraden und Gegenangriffen), sinken zusammen, ziehen ein Bein oder den unbewaffneten Arm zur Körpermitte.

=== Beweglichkeitstraining
